#!/bin/sh

TARGET="autogenerated.py"

cp $TARGET bak/
pyuic4 gui.ui > $TARGET
pyuic4 scenegraph.ui >> $TARGET
pyuic4 entityinspector.ui >> $TARGET

# replace NoDockWidgetArea with RightDockWidgetArea
sed -i s/NoDock/RightDock/ $TARGET

# remove import gui_rc
sed -i "/import gui_rc/d" $TARGET

# fix plugins imports
sed -i s/"from entityinspector"/"from gui.qt.plugins.entityinspector"/
sed -i s/"from scenegraphview"/"from gui.qt.plugins.scenegraphview"/

# to remove repeated imports and comments
vi $TARGET
