# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'track_editor.ui'
#
# Created: Mon Feb  2 20:35:57 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.tileEditorViewContainer = QtGui.QScrollArea(self.centralwidget)
        self.tileEditorViewContainer.setGeometry(QtCore.QRect(0, 0, 791, 521))
        self.tileEditorViewContainer.setMinimumSize(QtCore.QSize(662, 0))
        self.tileEditorViewContainer.setWidgetResizable(True)
        self.tileEditorViewContainer.setObjectName("tileEditorViewContainer")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.tileEditorViewContainer)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1200, 1200))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(1200, 1200))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tileEditorView = TileEditorView(self.scrollAreaWidgetContents)
        self.tileEditorView.setGeometry(QtCore.QRect(9, 9, 1200, 1200))
        self.tileEditorView.setMinimumSize(QtCore.QSize(1200, 1200))
        self.tileEditorView.setObjectName("tileEditorView")
        self.tileEditorViewContainer.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setCheckable(True)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPreview = QtGui.QAction(MainWindow)
        self.actionPreview.setCheckable(False)
        self.actionPreview.setObjectName("actionPreview")
        self.actionDirectionMode = QtGui.QAction(MainWindow)
        self.actionDirectionMode.setCheckable(True)
        self.actionDirectionMode.setChecked(True)
        self.actionDirectionMode.setObjectName("actionDirectionMode")
        self.actionElevationMode = QtGui.QAction(MainWindow)
        self.actionElevationMode.setCheckable(True)
        self.actionElevationMode.setObjectName("actionElevationMode")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPreview)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDirectionMode)
        self.toolBar.addAction(self.actionElevationMode)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Track Editor 0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreview.setText(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDirectionMode.setText(QtGui.QApplication.translate("MainWindow", "DirectionMode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionElevationMode.setText(QtGui.QApplication.translate("MainWindow", "ElevationMode", None, QtGui.QApplication.UnicodeUTF8))

from gui.qt.plugins.tileeditorview import TileEditorView
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'track_tools.ui'
#
# Created: Mon Feb  2 20:35:57 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_toolsDock(object):
    def setupUi(self, toolsDock):
        toolsDock.setObjectName("toolsDock")
        toolsDock.resize(133, 250)
        toolsDock.setMinimumSize(QtCore.QSize(130, 36))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.tilesNumber = QtGui.QLCDNumber(self.dockWidgetContents)
        self.tilesNumber.setGeometry(QtCore.QRect(1, 11, 129, 60))
        self.tilesNumber.setObjectName("tilesNumber")
        self.line = QtGui.QFrame(self.dockWidgetContents)
        self.line.setGeometry(QtCore.QRect(1, 77, 129, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(self.dockWidgetContents)
        self.line_2.setGeometry(QtCore.QRect(1, 151, 129, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget = QtGui.QWidget(self.dockWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 86, 129, 59))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.actionLeft = QtGui.QToolButton(self.layoutWidget)
        self.actionLeft.setCheckable(True)
        self.actionLeft.setAutoRaise(True)
        self.actionLeft.setArrowType(QtCore.Qt.LeftArrow)
        self.actionLeft.setObjectName("actionLeft")
        self.gridLayout.addWidget(self.actionLeft, 0, 0, 2, 1)
        self.actionForward = QtGui.QToolButton(self.layoutWidget)
        self.actionForward.setCheckable(True)
        self.actionForward.setChecked(True)
        self.actionForward.setAutoRaise(True)
        self.actionForward.setArrowType(QtCore.Qt.UpArrow)
        self.actionForward.setObjectName("actionForward")
        self.gridLayout.addWidget(self.actionForward, 0, 1, 1, 1)
        self.actionRight = QtGui.QToolButton(self.layoutWidget)
        self.actionRight.setCheckable(True)
        self.actionRight.setAutoRaise(True)
        self.actionRight.setArrowType(QtCore.Qt.RightArrow)
        self.actionRight.setObjectName("actionRight")
        self.gridLayout.addWidget(self.actionRight, 0, 2, 2, 1)
        self.actionBackward = QtGui.QToolButton(self.layoutWidget)
        self.actionBackward.setCheckable(True)
        self.actionBackward.setAutoRaise(True)
        self.actionBackward.setArrowType(QtCore.Qt.DownArrow)
        self.actionBackward.setObjectName("actionBackward")
        self.gridLayout.addWidget(self.actionBackward, 1, 1, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.dockWidgetContents)
        self.layoutWidget1.setGeometry(QtCore.QRect(1, 160, 129, 60))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.slowButton = QtGui.QToolButton(self.layoutWidget1)
        self.slowButton.setStyleSheet("background-color: red;")
        self.slowButton.setCheckable(True)
        self.slowButton.setObjectName("slowButton")
        self.gridLayout_2.addWidget(self.slowButton, 0, 0, 1, 1)
        self.inverseButton = QtGui.QToolButton(self.layoutWidget1)
        self.inverseButton.setStyleSheet("background-color: yellow;")
        self.inverseButton.setCheckable(True)
        self.inverseButton.setObjectName("inverseButton")
        self.gridLayout_2.addWidget(self.inverseButton, 0, 1, 1, 1)
        self.jumpButton = QtGui.QToolButton(self.layoutWidget1)
        self.jumpButton.setStyleSheet("background-color: blue")
        self.jumpButton.setCheckable(True)
        self.jumpButton.setObjectName("jumpButton")
        self.gridLayout_2.addWidget(self.jumpButton, 0, 2, 1, 1)
        self.speedButton = QtGui.QToolButton(self.layoutWidget1)
        self.speedButton.setStyleSheet("background-color: green")
        self.speedButton.setCheckable(True)
        self.speedButton.setObjectName("speedButton")
        self.gridLayout_2.addWidget(self.speedButton, 1, 0, 1, 1)
        self.holeButton = QtGui.QToolButton(self.layoutWidget1)
        self.holeButton.setStyleSheet("background-color: black")
        self.holeButton.setCheckable(True)
        self.holeButton.setObjectName("holeButton")
        self.gridLayout_2.addWidget(self.holeButton, 1, 1, 1, 1)
        self.neutralButton = QtGui.QToolButton(self.layoutWidget1)
        self.neutralButton.setStyleSheet("background-color: white")
        self.neutralButton.setCheckable(True)
        self.neutralButton.setChecked(True)
        self.neutralButton.setObjectName("neutralButton")
        self.gridLayout_2.addWidget(self.neutralButton, 1, 2, 1, 1)
        toolsDock.setWidget(self.dockWidgetContents)

        self.retranslateUi(toolsDock)
        QtCore.QMetaObject.connectSlotsByName(toolsDock)

    def retranslateUi(self, toolsDock):
        toolsDock.setWindowTitle(QtGui.QApplication.translate("toolsDock", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLeft.setText(QtGui.QApplication.translate("toolsDock", "<-", None, QtGui.QApplication.UnicodeUTF8))
        self.actionForward.setText(QtGui.QApplication.translate("toolsDock", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRight.setText(QtGui.QApplication.translate("toolsDock", "->", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackward.setText(QtGui.QApplication.translate("toolsDock", "V", None, QtGui.QApplication.UnicodeUTF8))

